# Generated by Django 5.2.4 on 2025-09-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_emailverification_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodehistory',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
