# Generated by Django 5.2.4 on 2025-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_qrcodehistory_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodehistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
