# Generated by Django 5.2.4 on 2025-09-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_qrcodehistory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodehistory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
