# Generated by Django 5.2.4 on 2025-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_qrcodehistory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodehistory',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
