# Generated by Django 5.2.6 on 2026-02-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_qrcodehistory_scanned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
