# Generated by Django 5.2.6 on 2026-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_subscription_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='guide_videos/')),
            ],
        ),
    ]
