# Generated by Django 5.2.6 on 2026-03-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_guidevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodehistory',
            name='qr_type',
            field=models.CharField(choices=[('scan', 'Scan'), ('generate', 'Generate')], default='scan', max_length=20),
        ),
    ]
