# Generated by Django 5.2.6 on 2026-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_userprofile_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
